# BabelDOC Gemini API 配置文件
# 使用OpenAI兼容接口访问Gemini

[babeldoc]
# 基本设置
debug = false
lang-in = "en"
lang-out = "zh"
qps = 4
output = "./output"

# 使用OpenAI兼容接口访问Gemini
openai = true
openai-model = "gemini-pro"  # 或 "gemini-1.5-pro"
openai-base-url = "https://api.openai.com/v1"  # 替换为Gemini兼容接口
openai-api-key = "your-gemini-api-key-here"  # 您的Gemini API密钥

# PDF处理选项
split-short-lines = false
short-line-split-factor = 0.8
skip-clean = false
dual-translate-first = false
disable-rich-text-translate = false
use-alternating-pages-dual = false
watermark-output-mode = "watermarked"
max-pages-per-part = 50
only-include-translated-page = false

# 扫描文档处理
skip-scanned-detection = false
ocr-workaround = false
auto-enable-ocr-workaround = false

# 翻译选项
no-dual = false
no-mono = false
min-text-length = 5
ignore-cache = false

# 术语表选项
auto-extract-glossary = true
save-auto-extracted-glossary = false

# 性能优化
pool-max-workers = 8
report-interval = 0.1

# 高级选项
translate-table-text = false
show-char-box = false
skip-form-render = false
skip-curve-render = false
only-parse-generate-pdf = false

# 公式和样式处理
formular-font-pattern = ""
formular-char-pattern = ""
remove-non-formula-lines = false
non-formula-line-iou-threshold = 0.9
figure-table-protection-threshold = 0.9

# 字体设置
primary-font-family = ""

# 兼容性增强
enhance-compatibility = false
